name: deborah
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5-1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  csv: ^5.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.4.0
  flutter_riverpod: ^1.0.4
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  yaru: ^0.4.3
  yaru_icons: ^0.2.6
  yaru_widgets: ^2.0.0-beta-1

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/resources/
